spring:
  profiles:
    active:
    - prod
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  web:
    resources:
      add-mappings: false
server:
  error:
    path: /public/error
    whitelabel:
      enabled: false
      
app:
  firebase:
    credential:
      path: ${APP_FIREBASE_CREDENTIAL_URI}
