spring:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  web:
    resources:
      add-mappings: false
server:
  error:
    whitelabel:
      enabled: false
app:
  firebase:
    credential:
      path: ${APP_FIREBASE_CREDENTIAL_PATH}
